name: One Piece Auto Poster

on:
  schedule:
    - cron: '0 * * * *' # Gira automaticamente ogni ora
  workflow_dispatch: # Ti permette di avviarlo a mano premendo il tasto su GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installa dipendenze
      run: |
        pip install python-telegram-bot feedparser requests pillow

    - name: Esegui lo Script Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python bot.py

    - name: Salva lo storico dei post (Evita duplicati al prossimo avvio)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        touch posted_urls.txt
        git add posted_urls.txt
        git commit -m "Aggiornato storico post inviati [skip ci]" || exit 0
        git push
